<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:property name="camera_height" value="1.13"/>
        <xacro:property name="camera_x" value="0.05"/>
        <xacro:property name="camera_angle" value="0.5235987755982988"/> 
    <joint name="camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_link"/>
        <origin xyz="${camera_x} 0 ${camera_height+0.05}" rpy="0 ${camera_angle} 0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.0010 0.01 0.01"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>


    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"></link>





</robot>